include "globals.t"
include "infrastructure.t"
include "..\\..\\Classes\\projectile.t"
include "..\\..\\Classes\\turret.t"
include "..\\..\\Classes\\enemy.t"
include "class_vars.t"
include "interface.t"
